# package setup
library(usethis)
create_package("/workspace/workspace_pipelines/blaseRtools")
use_mit_license("Brad Blaser")
use_package("DESeq2", type = "suggests")
use_package("DoubletFinder", type = "suggests")
use_package("tidyverse", type = "imports")
use_package("monocle3", type = "suggest")
use_package("cowplot", type = "imports")
use_package("readxl", type = "suggests")
use_package("fastSave", type = "suggests")
use_package("MASS", type = "suggest")
use_package("Matrix", type = "suggests")
use_package("Matrix.utils", type = "suggests")
use_package("Seurat", type = "suggests")
use_package("SeuratDisk", type = "suggests")
use_package("SingleCellExperiment", type = "suggests")
use_package("broom", type = "suggests")
use_package("ggpubr", type = "imports")
use_package("ggrepel", type = "imports")
use_package("grid", type = "imports")
use_package("hexbin", type = "suggests")
use_package("pheatmap", type = "suggests")
use_package("rrvgo", type = "suggests")
use_package("topGO", type = "suggests")
use_package("scater", type = "suggests")
use_package("huxtable", type = "suggests")
use_package("stats", type = "imports")
use_package("org.Hs.eg.db", type = "Suggests")
use_package("org.Dr.eg.db", type = "Suggests")
use_package("org.Mm.eg.db", type = "Suggests")
use_readme_md()
use_news_md()
use_git()
use_github()
use_data_raw()


check()
document()
install()
