# package setup
library(usethis)
create_package("/workspace/workspace_pipelines/blaseRtools")
use_mit_license("Brad Blaser")
use_package("DESeq2", type = "suggests")
use_package("DoubletFinder", type = "suggests")
use_package("tidyverse", type = "imports")
use_package("monocle3", type = "imports")
use_package("cowplot", type = "imports")
use_package("readxl", type = "imports")
use_package("fastSave", type = "imports")
use_package("MASS", type = "imports")
use_package("Matrix", type = "imports")
use_package("Matrix.utils", type = "imports")
use_package("Seurat", type = "imports")
use_package("SeuratDisk", type = "imports")
use_package("SingleCellExperiment", type = "imports")
use_package("broom", type = "imports")
use_package("ggpubr", type = "imports")
use_package("ggrepel", type = "imports")
use_package("grid", type = "imports")
use_package("hexbin", type = "imports")
use_package("pheatmap", type = "imports")
use_package("rrvgo", type = "imports")
use_package("topGO", type = "imports")
use_package("scater", type = "imports")
use_package("huxtable", type = "imports")
use_package("stats", type = "imports")
use_package("org.Hs.eg.db", type = "suggests")
use_package("org.Dr.eg.db", type = "suggests")
use_package("org.Mm.eg.db", type = "suggests")
use_package("dplyr", type = "imports")
use_package("ggplot2", type = "imports")
use_package("ggplot2", type = "imports")
use_package("renv", type = "imports")
use_package("stringr", type = "imports")
use_package("methods", type = "imports")
use_package("circlize", type = "imports")
use_package("GenomicRanges", type = "imports")
use_package("GenomicAlignments", type = "imports")
use_package("Rsamtools", type = "imports")
usethis::use_package("Signac", type = "imports")
use_readme_md()
use_news_md()
use_git()
use_github()
use_data_raw()
use_vignette(name = "scRNAseq")

# renv::init()
# renv::deactivate()

devtools::load_all()
devtools::check(cran = FALSE)
devtools::document()
# commit and push to github
renv::install(packages = "blaserlab/blaseRtools", library = "/usr/lib/R/site-library")
